# 这个入门工作流程是为在多个平台上运行的 CMake 项目准备的。如果你只需要一个单一平台的工作流程，请使用其他入门工作流程。
# 参见: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
名称：在多个平台上使用 CMake

在:
  推送:
    分支: [ "master" ]
  拉取请求:
    分支: [ "master" ]

工作:
  构建:
    运行于: ${{ matrix.os }}

    战略：
      # 将 fail-fast 设置为 false 以确保为所有矩阵组合提供反馈。当您的工作流程稳定时，请考虑将其更改为 true。
      快速失败：否

      # 设置一个矩阵来运行以下3种配置：
      # 1. 
      # 2. 
      # 3. 
      #
      # 要添加更多的构建类型（发布版、调试版、带调试信息的发布版等），请自定义 build_type 列表。
      矩阵:
        os: [ubuntu-latest, windows-latest]
        构建类型: [发布版]
        c 编译器: [gcc, clang, cl]
        包含:
          - 操作系统: Windows-latest
            c 编译器: cl
            cpp_compiler: cl
          - 操作系统: ubuntu-latest
            c 编译器: gcc
            cpp_compiler: g++
          - 操作系统: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }}
